package com.daixiaobao.greenrobot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table daixiaobao_afterSales.
 */
public class AfterSales {

    private Long id;
    /** Not-null value. */
    private String afterSalesId;
    private String name;

    public AfterSales() {
    }

    public AfterSales(Long id) {
        this.id = id;
    }

    public AfterSales(Long id, String afterSalesId, String name) {
        this.id = id;
        this.afterSalesId = afterSalesId;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAfterSalesId() {
        return afterSalesId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAfterSalesId(String afterSalesId) {
        this.afterSalesId = afterSalesId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
