package com.daixiaobao.greenrobot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table daixiaobao_brand.
 */
public class Brand {

    private Long id;
    /** Not-null value. */
    private String brandId;
    private String name;

    public Brand() {
    }

    public Brand(Long id) {
        this.id = id;
    }

    public Brand(Long id, String brandId, String name) {
        this.id = id;
        this.brandId = brandId;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getBrandId() {
        return brandId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
