package com.daixiaobao.greenrobot;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.daixiaobao.greenrobot.Group;
import com.daixiaobao.greenrobot.Attrb;
import com.daixiaobao.greenrobot.Feature;
import com.daixiaobao.greenrobot.AfterSales;
import com.daixiaobao.greenrobot.Brand;

import com.daixiaobao.greenrobot.GroupDao;
import com.daixiaobao.greenrobot.AttrbDao;
import com.daixiaobao.greenrobot.FeatureDao;
import com.daixiaobao.greenrobot.AfterSalesDao;
import com.daixiaobao.greenrobot.BrandDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupDaoConfig;
    private final DaoConfig attrbDaoConfig;
    private final DaoConfig featureDaoConfig;
    private final DaoConfig afterSalesDaoConfig;
    private final DaoConfig brandDaoConfig;

    private final GroupDao groupDao;
    private final AttrbDao attrbDao;
    private final FeatureDao featureDao;
    private final AfterSalesDao afterSalesDao;
    private final BrandDao brandDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupDaoConfig = daoConfigMap.get(GroupDao.class).clone();
        groupDaoConfig.initIdentityScope(type);

        attrbDaoConfig = daoConfigMap.get(AttrbDao.class).clone();
        attrbDaoConfig.initIdentityScope(type);

        featureDaoConfig = daoConfigMap.get(FeatureDao.class).clone();
        featureDaoConfig.initIdentityScope(type);

        afterSalesDaoConfig = daoConfigMap.get(AfterSalesDao.class).clone();
        afterSalesDaoConfig.initIdentityScope(type);

        brandDaoConfig = daoConfigMap.get(BrandDao.class).clone();
        brandDaoConfig.initIdentityScope(type);

        groupDao = new GroupDao(groupDaoConfig, this);
        attrbDao = new AttrbDao(attrbDaoConfig, this);
        featureDao = new FeatureDao(featureDaoConfig, this);
        afterSalesDao = new AfterSalesDao(afterSalesDaoConfig, this);
        brandDao = new BrandDao(brandDaoConfig, this);

        registerDao(Group.class, groupDao);
        registerDao(Attrb.class, attrbDao);
        registerDao(Feature.class, featureDao);
        registerDao(AfterSales.class, afterSalesDao);
        registerDao(Brand.class, brandDao);
    }
    
    public void clear() {
        groupDaoConfig.getIdentityScope().clear();
        attrbDaoConfig.getIdentityScope().clear();
        featureDaoConfig.getIdentityScope().clear();
        afterSalesDaoConfig.getIdentityScope().clear();
        brandDaoConfig.getIdentityScope().clear();
    }

    public GroupDao getGroupDao() {
        return groupDao;
    }

    public AttrbDao getAttrbDao() {
        return attrbDao;
    }

    public FeatureDao getFeatureDao() {
        return featureDao;
    }

    public AfterSalesDao getAfterSalesDao() {
        return afterSalesDao;
    }

    public BrandDao getBrandDao() {
        return brandDao;
    }

}
