package com.daixiaobao.greenrobot;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table daixiaobao_feature.
 */
public class Feature {

    private Long id;
    /** Not-null value. */
    private String featureId;
    private String featureName;
    private String attrb_id;

    public Feature() {
    }

    public Feature(Long id) {
        this.id = id;
    }

    public Feature(Long id, String featureId, String featureName, String attrb_id) {
        this.id = id;
        this.featureId = featureId;
        this.featureName = featureName;
        this.attrb_id = attrb_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFeatureId() {
        return featureId;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFeatureId(String featureId) {
        this.featureId = featureId;
    }

    public String getFeatureName() {
        return featureName;
    }

    public void setFeatureName(String featureName) {
        this.featureName = featureName;
    }

    public String getAttrb_id() {
        return attrb_id;
    }

    public void setAttrb_id(String attrb_id) {
        this.attrb_id = attrb_id;
    }

}
